import cv2
import matplotlib.pyplot as plt 
img=cv2.imread("D:/7040/dropcol.jpeg",cv2.IMREAD_REDUCED_COLOR_4)
imgRGB=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
ksize=(3,3)
k3blur=cv2.blur(gray,ksize)
ksize=(5,5)
k5blur=cv2.blur(gray,ksize)
ksize=(15,15)
k15blur=cv2.blur(gray,ksize)
ksize=(25,25)
k25blur=cv2.blur(gray,ksize)
plt.subplot(242),plt.imshow(imgRGB,cmap='gray'),plt.title('Original Image'),plt.axis('off')
plt.subplot(243),plt.imshow(gray,cmap='gray'),plt.title('Grayscale Image'),plt.axis('off')
plt.subplot(245),plt.imshow(k3blur,cmap='gray'),plt.title('Kernel Size 3'),plt.axis('off')
plt.subplot(246),plt.imshow(k5blur,cmap='gray'),plt.title('Kernel Size 5'),plt.axis('off')
plt.subplot(247),plt.imshow(k15blur,cmap='gray'),plt.title('Kernel Size 15'),plt.axis('off')
plt.subplot(248),plt.imshow(k25blur,cmap='gray'),plt.title('Kernel Size 25'),plt.axis('off')
plt.show()